#!/bin/bash
#
#  Procedure to be run once to initialize the GW for Kura
#
#
KURADIR=/opt/eclipse/kura

# copy the specific plugins
cp -vf ../plugins/*.jar $KURADIR/plugins
#
# remove all snapŝhots and copy the snapshot 0
#
rm -vf $KURADIR/user/snapshots/snap*
#
#  generate and copy properties and snapshot_0
#
python gen_kura_properties.py

cp -vf kura.properties $KURADIR/framework

# ready


