#
#  Base file for SolidSense provisioning V1.2
#
#  Copyright SolidSense-Connect 2021-2022
#
#  that file provide the basic minimum configuration for Kura and all SolidSense services
#  It shall be located in /opt/SolidSense/config and named SolidSense-conf-base.yml
#
#  The customer specific configuration is located in /data/solidsense/config/SolidSense-conf-custom.yml
#  The combination of both files will be applied to the gateway
#
#  mini language
#
#   state is used for activable services (pure data services don't need one)
#   disabled    the service will not be configured and and started
#   auto        the service is configured but the start and activation is done by another process or context dependant
#   interactive the service configuration is to be done via Kura
#   active      the service is configured and activared during provisioning
#
#   override    (true by default) replace the default service definition, false, combine both definitions
# Global variable definition
gateway:
    # if the gateway-id is set it will be used as is for all transport service
    # gateway-id: $SERIAL-NUMBER
    # here are all the default variable that are created implicitely
    # SERIAL-NUMBER     serial number of the gateway
    # PART-NUM          full part number including variant
    # MODEL-ID          product code
    # MODEL-NAME        Description of hardware configuration
    # FIRMWARE          Actual firmware running
    
    snapshot_0: snapshot_0.xml
    # mode can be normal or test. In test mode all files are generated in /temp directory
    mode: normal 
#
#
#  Services definition
#
services:

- service:
    # MQTT connection to Kapua
    type: KuraService
    name: KapuaMQTT
    state: active
    parameters:
        configuration: MqttDataTransport
    properties:
        broker-url: mqtts://kapua.solidsense.io:8883
        topic.context.account-name: SOLIDSENSE-NURSERY
        username: newborn-gw
        password: ^$SolidSense2019$
        client-id: $SERIAL-NUMBER
        
- service:
    # Data service (MQTT) parameters
    type: KuraService
    name: MqttData
    parameters:
        configuration: DataService
    properties:
        connect.auto-on-startup: true
        
- service:
    # NTP connection
    type: KuraService
    name: Clock
    parameters:
        configuration: ClockService
    properties:
        enabled: true
        
- service:
    type: KuraService
    name: CommandService
    state: active
    parameters:
        configuration: CommandCloudApp
    properties:
        command.enable: true
        privileged.command.service.enable: true
        # command.working.directory:
        # command.environment:
        command.timeout: 120
        # command.password.value

- service:
    # Local loop
    type: NetworkService
    name: lo
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    properties:
        config.ip4.status: netIPv4StatusEnabledLAN
        config.state: ACTIVATED
        
        
#
#  Default network configuration
#   WAN => eth0  & DHCP client
#   LAN => tun0  & no DHCP
#   LAN => tap0  & no DHCP
#   LAN => wlan0 & DHCP Server
#   LAN => ppp0  & DHCP client

# Ethernet eth0
- service:
    type: NetworkService
    name: eth0
    state: active
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    variables:
    properties:
        config.ip4.status: netIPv4StatusEnabledWAN
        config.dhcpClient4.enabled: true
        config.dhcpServer4.enabled: false
        config.autoconnect: true

# Tunneling tun0
- service:
    type: NetworkService
    name: tun0
    state: active
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    variables:
    properties:
        config.ip4.status: netIPv4StatusEnabledLAN
        config.dhcpClient4.enabled: false
        config.dhcpServer4.enabled: false
        config.autoconnect: true

# Tunneling tap0
- service:
    type: NetworkService
    name: tap0
    state: active
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    variables:
    properties:
        config.ip4.status: netIPv4StatusEnabledLAN
        config.dhcpClient4.enabled: false
        config.dhcpServer4.enabled: false
        config.autoconnect: true

#
#   WiFi configuration by default
#   Access point
#   HW mode=g. Higher mode not yet supported by KuraService
#
- service:
    type: WiFiService
    name: wlan0
    state: active
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    variables:
        WPA_KEYMGMT: WPA-PSK
        WIFI_PASSWORD: testKEYS
        WPA_LEVEL: 2
        WPA_PAIRWISE: CCMP
        WIFI_MODE: g
        WIFI_CHANNEL: 5
        WLAN-INTERFACE: $service_name
        
    properties:
        config.wifi.mode: MASTER
        config.state: ACTIVATED
        config.ip4.status: netIPv4StatusEnabledLAN
        config.wifi.master.mode: MASTER
        config.dhcpServer4.passDns: true
        config.nat.enabled: true
        config.wifi.master.securityType: SECURITY_WPA2
        config.wifi.master.ssid: $SERIAL-NUMBER
        config.wifi.master.passphrase: $WIFI_PASSWORD
        config.wifi.master.pairwiseCiphers: $WPA_PAIRWISE
        config.wifi.master.radioMode: RADIO_MODE_80211$WIFI_MODE
        config.ip4.address: 172.16.1.1
        config.dhcpServer4.enabled: true
        config.dhcpServer4.rangeStart: 172.16.1.100
        config.dhcpServer4.rangeEnd: 172.16.1.115
#
# Firewall
#
- service:
    type: FirewallService
    name: firewall
    state: active
    parameters:
        configuration: FirewallConfigurationService
        allowed_networks: "127.0.0.1/32"
        #firewall_def: "Firewall definition string (see Kura)"
    properties:
        firewall.open.ports: 22,tcp,,,,,,#;53,udp,,eth0,,,,#;53,udp,,wlan0,,,,#;67,udp,,eth0,,,,#;67,udp,,wlan0,,,,#;443,tcp,,eth0,,,,#;443,tcp,,wlan0,,,,#;1450,tcp,,eth0,,,,#;1450,tcp,,wlan0,,,,#;4443,tcp,,eth0,,,,#;4443,tcp,,wlan0,,,,#;5002,tcp,127.0.0.1/32,,,,,#;8000,tcp,,eth0,,,,#;8000,tcp,,wlan0,,,,#;53,udp,,ppp0,,,,#;67,udp,,ppp0,,,,#;443,tcp,,ppp0,,,,#;1450,tcp,,ppp0,,,,#;4443,tcp,,ppp0,,,,#;8000,tcp,,ppp0,,,,#;443,tcp,,tap0,,,,#;443,tcp,,tun0,,,,#
#
#   Modem/GPS service
#
# activated when a modem is detected
#
#  Global variable created by the modem_gps service
#
#   MODEM_MFG   name of the manufacturer
#   MODEM_MODEL model name
#   MODEM_IMEI
#   MODEM_SIM_IN    true if a SIM is present, false otherwise
#
- service:
    type: ModemGps
    name: modem_gps
    state: auto
    parameters:
        system: modem_gps
        port: 20231
        address: 0.0.0.0
        modem_ctrl: /dev/ttyUSB2
        nmea_tty: /dev/ttyUSB1
        trace: info
        PIN: '0000' # this for example - the PIN is used only if the SIM card request it
        roaming: true
        operatorsDB: 'operatorsDB'
        start_gps: false
        timer: 60
        nb_retry: 5
#
#  ppp0 basic configuration
# 
- service:
    type: PppService
    name: ppp0
    state: disabled
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    variables:
        APN: None
        APN_AUTH: None
        APN_USER: 
        APN_PASSWORD:
        DIAL_STRING: atd*99***#
    properties:
        config.pppNum: 0
        #config.apn: $APN
        #config.authType: $APN_AUTH
        #config.identifier: $MODEM_MODEL
        #config.username: $APN_USER
        #config.password: $APN_PASSWORD
        #config.dialString: $DIAL_STRING
        #config.ip4.status: netIPv4StatusDisabled
        #config.dhcpClient4.enabled: true
        #config.enabled: true
        #config.autoconnect: true
        #usb.product.name: $MODEM_MODEL
        #usb.vendor.name: $MODEM_MFG
        #model: $MODEM_MODEL
        #manufacturer: $MODEM_MFG
        

#
#   For continuity Wirepas and Bluetooth services are declared in interactive mode
#
#
#   hci0 on TI WL1831 on internal interface
#   to be configured via Kura
#      
- service:
    type: BluetoothService
    name: hci0
    state: active
    parameters:
        interface: $service_name
        port: internal

- service:
    type: BLEClientService
    name: BLE-Client
    parameters:
        interface: hci0
        max_connect: 10
        notif_mtu: 63
        trace: info
        debug_bluez: false

#
#   SolidSense MQTT Services
#
- service:
    type: MQTTService
    name: mqtt1
    state: interactive
    parameters:
        configuration: SolidsenseMqttService
        plugin: SolidsenseMqttService.dp  # To be further investigated why we shall have that only for the MQTT agent
        plugin_name: SolidsenseMqttService
        system: solidsense_mqtt
        prefix: transport
    variables:
        ENABLE: false           #change following issue 630
        SECURE: False
        ADDRESS: TO_BE_CONFIGURED
        PORT: 1883
        USER: solidsense
        PASSWORD: solidsense
    properties:
        enabled: $ENABLE
        secured: $SECURE
        address: $ADDRESS
        user: $USER
        port: $PORT
        passwd: $PASSWORD
        persist: true
        maxpacket: 1000
        maxdelay: 1800
        ble: false
        modemgps: true
        autostart: false
        obd: false
        obddongle: OBD
