#!/bin/bash
#
#  install file for solid sense system
#  to be run once on SW installation on the GW
#  or upon container initialization
#
SOLIDSENSE=/opt/SolidSense
#
#  configure Kura
#
cd $SOLIDSENSE/kura/config
./solid_kura_config
#
#  install qmm
#
cd $SOLIDSENSE/utilities
cp -fv qmm/qmm_launcher /usr/bin/qmm
chmod a+x /usr/bin/qmm
#
#  regenrate the hostapd-wlan0.conf file
#
cd repair
./repair_wifi
