#!/bin/bash
# copy the configuration files in the target environement
#
cp ../config/* /opt/SolidSense/config
cp -r ../template/* /opt/SolidSense/template
cp ../custom/SolidSense-conf-custom.yml /data/solidsense/config
