# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_service.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12grpc_service.proto\"\x0f\n\rVoidParameter\"\xe8\x01\n\rSendPacketReq\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.VoidParameter\x12\x1b\n\x13\x64\x65stination_address\x18\x02 \x02(\r\x12\x17\n\x0fsource_endpoint\x18\x03 \x02(\r\x12\x1c\n\x14\x64\x65stination_endpoint\x18\x04 \x02(\r\x12\x0b\n\x03qos\x18\x05 \x02(\r\x12\x0f\n\x07payload\x18\x06 \x02(\x0c\x12\x18\n\x10initial_delay_ms\x18\x07 \x01(\r\x12\x18\n\x10is_unack_csma_ca\x18\x08 \x01(\x08\x12\x11\n\thop_limit\x18\t \x01(\r\"\x9a\x02\n\x13PacketReceivedEvent\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.VoidParameter\x12\x16\n\x0esource_address\x18\x02 \x02(\r\x12\x1b\n\x13\x64\x65stination_address\x18\x03 \x02(\r\x12\x17\n\x0fsource_endpoint\x18\x04 \x02(\r\x12\x1c\n\x14\x64\x65stination_endpoint\x18\x05 \x02(\r\x12\x16\n\x0etravel_time_ms\x18\x06 \x02(\r\x12\x18\n\x10rx_time_ms_epoch\x18\x07 \x01(\x04\x12\x0b\n\x03qos\x18\x08 \x02(\r\x12\x0f\n\x07payload\x18\t \x01(\x0c\x12\x14\n\x0cpayload_size\x18\n \x01(\r\x12\x11\n\thop_count\x18\x0b \x01(\r2z\n\x10WirepasConnector\x12\x36\n\nGetPackets\x12\x0e.VoidParameter\x1a\x14.PacketReceivedEvent\"\x00\x30\x01\x12.\n\nSendPacket\x12\x0e.SendPacketReq\x1a\x0e.VoidParameter\"\x00')
)




_VOIDPARAMETER = _descriptor.Descriptor(
  name='VoidParameter',
  full_name='VoidParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=37,
)


_SENDPACKETREQ = _descriptor.Descriptor(
  name='SendPacketReq',
  full_name='SendPacketReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SendPacketReq.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_address', full_name='SendPacketReq.destination_address', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_endpoint', full_name='SendPacketReq.source_endpoint', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_endpoint', full_name='SendPacketReq.destination_endpoint', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qos', full_name='SendPacketReq.qos', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='SendPacketReq.payload', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_delay_ms', full_name='SendPacketReq.initial_delay_ms', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_unack_csma_ca', full_name='SendPacketReq.is_unack_csma_ca', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hop_limit', full_name='SendPacketReq.hop_limit', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=272,
)


_PACKETRECEIVEDEVENT = _descriptor.Descriptor(
  name='PacketReceivedEvent',
  full_name='PacketReceivedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='PacketReceivedEvent.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_address', full_name='PacketReceivedEvent.source_address', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_address', full_name='PacketReceivedEvent.destination_address', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_endpoint', full_name='PacketReceivedEvent.source_endpoint', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_endpoint', full_name='PacketReceivedEvent.destination_endpoint', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='travel_time_ms', full_name='PacketReceivedEvent.travel_time_ms', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rx_time_ms_epoch', full_name='PacketReceivedEvent.rx_time_ms_epoch', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qos', full_name='PacketReceivedEvent.qos', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PacketReceivedEvent.payload', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_size', full_name='PacketReceivedEvent.payload_size', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hop_count', full_name='PacketReceivedEvent.hop_count', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=557,
)

_SENDPACKETREQ.fields_by_name['header'].message_type = _VOIDPARAMETER
_PACKETRECEIVEDEVENT.fields_by_name['header'].message_type = _VOIDPARAMETER
DESCRIPTOR.message_types_by_name['VoidParameter'] = _VOIDPARAMETER
DESCRIPTOR.message_types_by_name['SendPacketReq'] = _SENDPACKETREQ
DESCRIPTOR.message_types_by_name['PacketReceivedEvent'] = _PACKETRECEIVEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoidParameter = _reflection.GeneratedProtocolMessageType('VoidParameter', (_message.Message,), dict(
  DESCRIPTOR = _VOIDPARAMETER,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:VoidParameter)
  ))
_sym_db.RegisterMessage(VoidParameter)

SendPacketReq = _reflection.GeneratedProtocolMessageType('SendPacketReq', (_message.Message,), dict(
  DESCRIPTOR = _SENDPACKETREQ,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:SendPacketReq)
  ))
_sym_db.RegisterMessage(SendPacketReq)

PacketReceivedEvent = _reflection.GeneratedProtocolMessageType('PacketReceivedEvent', (_message.Message,), dict(
  DESCRIPTOR = _PACKETRECEIVEDEVENT,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:PacketReceivedEvent)
  ))
_sym_db.RegisterMessage(PacketReceivedEvent)



_WIREPASCONNECTOR = _descriptor.ServiceDescriptor(
  name='WirepasConnector',
  full_name='WirepasConnector',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=559,
  serialized_end=681,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPackets',
    full_name='WirepasConnector.GetPackets',
    index=0,
    containing_service=None,
    input_type=_VOIDPARAMETER,
    output_type=_PACKETRECEIVEDEVENT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendPacket',
    full_name='WirepasConnector.SendPacket',
    index=1,
    containing_service=None,
    input_type=_SENDPACKETREQ,
    output_type=_VOIDPARAMETER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WIREPASCONNECTOR)

DESCRIPTOR.services_by_name['WirepasConnector'] = _WIREPASCONNECTOR

# @@protoc_insertion_point(module_scope)
