# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_service_pb2 as grpc__service__pb2


class WirepasConnectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPackets = channel.unary_stream(
        '/WirepasConnector/GetPackets',
        request_serializer=grpc__service__pb2.VoidParameter.SerializeToString,
        response_deserializer=grpc__service__pb2.PacketReceivedEvent.FromString,
        )
    self.SendPacket = channel.unary_unary(
        '/WirepasConnector/SendPacket',
        request_serializer=grpc__service__pb2.SendPacketReq.SerializeToString,
        response_deserializer=grpc__service__pb2.VoidParameter.FromString,
        )


class WirepasConnectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPackets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendPacket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WirepasConnectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPackets': grpc.unary_stream_rpc_method_handler(
          servicer.GetPackets,
          request_deserializer=grpc__service__pb2.VoidParameter.FromString,
          response_serializer=grpc__service__pb2.PacketReceivedEvent.SerializeToString,
      ),
      'SendPacket': grpc.unary_unary_rpc_method_handler(
          servicer.SendPacket,
          request_deserializer=grpc__service__pb2.SendPacketReq.FromString,
          response_serializer=grpc__service__pb2.VoidParameter.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'WirepasConnector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
